services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Hfm\Kursanmeldung\:
    resource: '..\Classes\*'
    exclude: '..\Classes\Domain\Model\*'
  Hfm\Kursanmeldung\Controller\GeneralController:
    public: true
  Hfm\Kursanmeldung\Controller\GebuehrenController:
    public: true
  Hfm\Kursanmeldung\Domain\Repository\GebuehrenRepository:
    public: true
  Hfm\Kursanmeldung\Controller\HotelController:
    public: true
  Hfm\Kursanmeldung\Domain\Repository\HotelRepository:
    public: true
  Hfm\Kursanmeldung\Controller\KursanmeldungController:
    public: true
  Hfm\Kursanmeldung\Domain\Repository\KursanmeldungRepository:
    public: true
  Hfm\Kursanmeldung\Controller\OrteController:
    public: true
  Hfm\Kursanmeldung\Domain\Repository\OrteRepository:
    public: true
  Hfm\Kursanmeldung\Controller\ProfController:
    public: true
  Hfm\Kursanmeldung\Domain\Repository\ProfRepository:
    public: true
  Hfm\Kursanmeldung\Controller\KursController:
    public: true
  Hfm\Kursanmeldung\Domain\Repository\KursRepository:
    public: true
  Hfm\Kursanmeldung\Controller\KursListeController:
    public: true
  Hfm\Kursanmeldung\Controller\TeilnehmerController:
    public: true
  Hfm\Kursanmeldung\Domain\Repository\TeilnehmerRepository:
    public: true
  Hfm\Kursanmeldung\Domain\Repository\AnmeldestatusRepository:
    public: true
  Hfm\Kursanmeldung\Utility\PropertyConverterUtility:
    public: true
  Hfm\Kursanmeldung\Utility\FormatUtility:
    public: true
  Hfm\Kursanmeldung\Utility\SessionUtility:
    public: true
  Hfm\Kursanmeldung\Controller\FrontendController:
    public: true
    tags: ['backend.controller']
  Hfm\Kursanmeldung\Utility\ParticipantUtility:
    public: true
  Hfm\Kursanmeldung\App\Participant\Business\ParticipantFacade:
    public: true
  Hfm\Kursanmeldung\App\Participant\Business\ParticipantFactory:
    public: true
  Hfm\Kursanmeldung\App\Novalnet\Business\NovalnetFacade:
    public: true
  Hfm\Kursanmeldung\App\Novalnet\Business\NovalnetFactory:
    public: true
  Hfm\Kursanmeldung\App\Mail\Business\MailFacade:
    public: true
  Hfm\Kursanmeldung\App\Mail\Business\MailFactory:
    public: true
  Hfm\Kursanmeldung\App\Mail\Business\Reader\ContentReader:
    public: true
  Hfm\Kursanmeldung\App\Mail\Business\Hydrator\MailBodyHydrator:
    public: true


